In [1]:
import numpy as np

In [2]:
s = np.arange(15)
g = np.arange(20)

In [4]:
s
g

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [6]:
s = np.arange(15).reshape(3,5)
s

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [9]:
print(s.ndim)
print(s.shape)
print(s.size)
print(s.dtype)
print(s.itemsize)
print(type(s))

2
(3, 5)
15
int32
4
<class 'numpy.ndarray'>


In [12]:
g = np.array([1.0,2.0,3.0,4.0])
print(g)
print(g.dtype)
print(type(g))

[1. 2. 3. 4.]
float64
<class 'numpy.ndarray'>


In [13]:
c = np.eye(10)
dtupe=np.float64
c

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [15]:

d = np.linspace(-1,2,15,endpoint=True)
print(d)

[-1.         -0.78571429 -0.57142857 -0.35714286 -0.14285714  0.07142857
  0.28571429  0.5         0.71428571  0.92857143  1.14285714  1.35714286
  1.57142857  1.78571429  2.        ]


In [16]:
e = np.logspace(-1,2,15,endpoint=True,base=10)
print(e)

[  0.1          0.16378937   0.26826958   0.43939706   0.71968567
   1.17876863   1.93069773   3.16227766   5.17947468   8.48342898
  13.89495494  22.75845926  37.2759372   61.05402297 100.        ]


In [17]:
f=np.fromfunction(lambda i, j: i== j, (3, 3), dtype=int)
f

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [20]:
#creating arrays
s = np.arange(12).reshape(2,6)
print(s)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [21]:
s*2

array([[ 0,  2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20, 22]])

In [22]:
s+s

array([[ 0,  2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20, 22]])

In [23]:
s*s

array([[  0,   1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100, 121]])

In [25]:
g= s.transpose()
g

array([[ 0,  6],
       [ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11]])

In [26]:
s@g

array([[ 55, 145],
       [145, 451]])

In [28]:
print(s)
s.sum(axis=1)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


array([15, 51])

In [29]:
s.sum

<function ndarray.sum>

In [32]:
print(s.min(), s.max())

0 11


In [34]:
g = s*np.pi/12.0
print(g)

[[0.         0.26179939 0.52359878 0.78539816 1.04719755 1.30899694]
 [1.57079633 1.83259571 2.0943951  2.35619449 2.61799388 2.87979327]]


In [37]:
s = np.cos(s)
print(s)

[[ 1.          0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]
 [ 0.96017029  0.75390225 -0.14550003 -0.91113026 -0.83907153  0.0044257 ]]


In [38]:
sg = s + g

In [39]:
print(sg)

[[ 1.          0.80210169  0.10745194 -0.20459433  0.39355393  1.59265912]
 [ 2.53096661  2.58649797  1.94889507  1.44506423  1.77892235  2.88421896]]


In [45]:
s =np.arange(9)
s

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [47]:
s[3]

3

In [49]:
print(s[2:3])

[2]


In [51]:
s[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [53]:
#2d arrays
a = np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [54]:
a[1,1]

6

In [55]:
a[0:2,0:2]

array([[0, 1],
       [5, 6]])

In [56]:
a[:,1]

array([ 1,  6, 11])

In [57]:
a = a.flatten()

In [58]:
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [59]:
#print
for r in a:
    print(r)
a= np.arange(15).reshape(3,5)
print(a)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [62]:
for e in a.flat:
     print(e)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14


In [63]:
#copying arrays

a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [64]:
b = a 
b is a

True

In [65]:
b.shape = (2,5)
print(b)
a.shape

[[0 1 2 3 4]
 [5 6 7 8 9]]


(2, 5)

In [66]:
 b is a

True

In [67]:
print(a)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [68]:
a = np.arange(12)
c = a[:]
a.shape = (3,4)

print(a)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [69]:
c[1]= -1
print(a)
print(c)

[[ 0 -1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0 -1  2  3  4  5  6  7  8  9 10 11]


In [70]:
d = c[3:8]
print(d)

[3 4 5 6 7]


In [71]:
d[:] = 0

In [73]:
print(a)
print(c)
print(d)

[[ 0 -1  2  0]
 [ 0  0  0  0]
 [ 8  9 10 11]]
[ 0 -1  2  0  0  0  0  0  8  9 10 11]
[0 0 0 0 0]


In [74]:
print(c is a)
print(c.base is a)
print(c.flags.owndata)
print(a.flags.owndata)

False
True
False
True


In [75]:
#boolean
a = np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [76]:
a[a>4]=0
a

array([[0, 1, 2, 3, 4],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [77]:
a[a==0]= -1
a

array([[-1,  1,  2,  3,  4],
       [-1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1]])

In [78]:
a == -1

array([[ True, False, False, False, False],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [79]:
a = np.arange(12).reshape(3,4)
a[np.logical_and(a>3,a<=90)] = 0.0
a

array([[0, 1, 2, 3],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [80]:
a>4

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [81]:
M = 32
N= 64
xmin = 0.0
xmin = 0.0
xmin=ymin=0.0
xmax=ymax=1.0

x = np.linspace(xmin, xmax, M,endpoint=False)
y = np.linspace(xmin,xmax,N,endpoint=False)

print(x.shape)
print(y.shape)
y

(32,)
(64,)


array([0.      , 0.015625, 0.03125 , 0.046875, 0.0625  , 0.078125,
       0.09375 , 0.109375, 0.125   , 0.140625, 0.15625 , 0.171875,
       0.1875  , 0.203125, 0.21875 , 0.234375, 0.25    , 0.265625,
       0.28125 , 0.296875, 0.3125  , 0.328125, 0.34375 , 0.359375,
       0.375   , 0.390625, 0.40625 , 0.421875, 0.4375  , 0.453125,
       0.46875 , 0.484375, 0.5     , 0.515625, 0.53125 , 0.546875,
       0.5625  , 0.578125, 0.59375 , 0.609375, 0.625   , 0.640625,
       0.65625 , 0.671875, 0.6875  , 0.703125, 0.71875 , 0.734375,
       0.75    , 0.765625, 0.78125 , 0.796875, 0.8125  , 0.828125,
       0.84375 , 0.859375, 0.875   , 0.890625, 0.90625 , 0.921875,
       0.9375  , 0.953125, 0.96875 , 0.984375])

In [82]:
import time
import numpy as np
M = 32
N = 64

x = np.linspace(0.0, 1.0, M, endpoint=False)
y = np.linspace(0.0,1.0,N,endpoint=False)

In [85]:
t0 = time.time()

g=np.zeros((M,N))
for i in range(M):
    for j in range(N):
        g[i,j]=np.sin(2.0*np.pi*x[i]*y[j])
        
t1 = time.time()
print("time elapsed: {} s".format(t1-t0))
    

time elapsed: 0.008008003234863281 s


In [86]:
x2d, y2d = np.meshgrid(x, y, indexing="ij")

print(x2d[:,0])
print(x2d[0,:])

print(y2d[:,0])
print(y2d[0,:])

[0.      0.03125 0.0625  0.09375 0.125   0.15625 0.1875  0.21875 0.25
 0.28125 0.3125  0.34375 0.375   0.40625 0.4375  0.46875 0.5     0.53125
 0.5625  0.59375 0.625   0.65625 0.6875  0.71875 0.75    0.78125 0.8125
 0.84375 0.875   0.90625 0.9375  0.96875]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0.]
[0.       0.015625 0.03125  0.046875 0.0625   0.078125 0.09375  0.109375
 0.125    0.140625 0.15625  0.171875 0.1875   0.203125 0.21875  0.234375
 0.25     0.265625 0.28125  0.296875 0.3125   0.328125 0.34375  0.359375
 0.375    0.390625 0.40625  0.421875 0.4375   0.453125 0.46875  0.484375
 0.5      0.515625 0.53125  0.546875 0.5625   0.578125 0.59375  0.609375
 0.625    0.640625 0.65625  0.671875 0.6875   0.703125 0.71875  0.734375
 0.75     

In [89]:
t0 = time.time()
g2 = np.sin(2.0*np.pi*x2d*y2d)
t1 = time.time()
print("time elapsed: {} s".format(t1-t0))

time elapsed: 0.0010004043579101562 s


In [90]:
x = np.array([1,2,3,4])
y = np.array([4,3,2,1])
np.concatenate([y,x])

array([4, 3, 2, 1, 1, 2, 3, 4])

In [91]:
z = [9, 4,6]
print(np.concatenate([x,y,z]))

[1 2 3 4 4 3 2 1 9 4 6]


In [92]:
grid = np.array([[10,20,30],[40,50,60]])

In [93]:
np.concatenate([grid, grid])

array([[10, 20, 30],
       [40, 50, 60],
       [10, 20, 30],
       [40, 50, 60]])

In [94]:
np.concatenate([grid,grid],axis=1)

array([[10, 20, 30, 10, 20, 30],
       [40, 50, 60, 40, 50, 60]])

In [95]:
x = [1,2,3,4,4,3,2,1,9,4,6]
x1,x2,x3,x4 = np.split(x, [3,5,8])
print(x1,x2,x3,x4)


[1 2 3] [4 4] [3 2 1] [9 4 6]


In [96]:
grid = np.arange(25).reshape((5, 5))
grid

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [97]:
left ,right=np.hsplit(grid,[2])
print(left)
print(right)

[[ 0  1]
 [ 5  6]
 [10 11]
 [15 16]
 [20 21]]
[[ 2  3  4]
 [ 7  8  9]
 [12 13 14]
 [17 18 19]
 [22 23 24]]


In [98]:
x = np.arange(1,9)
print(x)
np.add.reduce(x)

[1 2 3 4 5 6 7 8]


36

In [99]:
np.multiply.reduce(x)

40320

In [100]:
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15, 21, 28, 36])

In [102]:
np.multiply.accumulate(x)

array([    1,     2,     6,    24,   120,   720,  5040, 40320])